### PR TITLE
reduce dependencies

### PR DESCRIPTION
**Pull request by strangiato**
Used for testing the pipeline for a faster build/execution of the pipeline that removes all of the pipeline specific packages.

I will switch this PR out of draft after I have had a chance to test it.

### CODE REVIEW

**Comment by strangiato** [comment]
Tested here:

https://console-openshift-console.apps.cluster-h9vfn.dynamic.redhatworkshops.io/k8s/ns/parasol-insurance/tekton.dev~v1~PipelineRun/model-retrain-98rthi

Full process time reduced to 6 min:

Screenshot 2024-06-10 at 11 45 47 AM

**Review by gutseb — COMMENTED** [review]
looks ok to me

**Comment by diego-torres** [comment]
we use ultralytics to train the model. Is not that a package required for the image that will run in step 3? Probably I would be more inclined to know if preparing an image with most of these packages could improve the s2i; having the s2i to add 1 package or 2, but the image to have packages that we will need and use.

**Comment by diego-torres** [comment]
from @strangiato at our slack channel:

I think a big part of it is deciding what you want them to get out of the exercise. Considering this is intended to be a quick intro I figured it was a decent compromise.

**Review by diego-torres — APPROVED** [review]

**Pull request merged**
